### ISSUE TITLE
Editar informações do Rodapé

### ISSUE THREAD

**Issue by batugadenator** [astatonn/ids-joomla-eb#8]
Olá, eu preciso substituir a informação do rodapé do site de "Desenvolvido por Sgt Souza Lima • Linkedin - 1o CTA"
O site da OM deverá conter em seu rodapé a publicação em Boletim Interno que autorizou a publicação na internet.
Não encontrei o caminho no código do tema.
Grato!!!

**Comment by nascimento019** [comment]
Olá, eu preciso substituir a informação do rodapé do site de "Desenvolvido por Sgt Souza Lima • Linkedin - 1o CTA" 

Não consegui achar no cógigo onde modifica

**Comment by astatonn** [comment]
Você pode inserir a informação na tag footer só editar o arquivo index php

**Comment by nascimento019** [comment]
Consegui editar, tem uma versão do template em html ou uma que não seja necessário a utilização do joomla ?

**Comment by batugadenator** [comment]
Obrigado

Em sáb., 19 de out. de 2024, 10:16, Nascimento019 ***@***.***>
escreveu:

**Comment by astatonn** [comment]
As informações são obtidas automaticamente, caso queiram, podem incluir as informações sobre a OM dentro da tag footer
